### ISSUE TITLE
Error running tool

### ISSUE THREAD

**Issue by AceHack** [StefanScherer/rebase-docker-image#1]
I get the following error

C:\Users\astainba\AppData\Roaming\npm\node_modules\rebase-docker-image\index.js:405
      }/blobs/${manifestSourceBase.config.digest}`,
                                          ^

TypeError: Cannot read property 'digest' of undefined
    at getConfigOfSourceBaseImage (C:\Users\astainba\AppData\Roaming\npm\node_modules\rebase-docker-image\index.js:405:43)
    at C:\Users\astainba\AppData\Roaming\npm\node_modules\rebase-docker-image\node_modules\async\dist\async.js:3866:24
    at replenish (C:\Users\astainba\AppData\Roaming\npm\node_modules\rebase-docker-image\node_modules\async\dist\async.js:998:17)
    at iterateeCallback (C:\Users\astainba\AppData\Roaming\npm\node_modules\rebase-docker-image\node_modules\async\dist\async.js:983:17)
    at C:\Users\astainba\AppData\Roaming\npm\node_modules\rebase-docker-image\node_modules\async\dist\async.js:958:16
    at C:\Users\astainba\AppData\Roaming\npm\node_modules\rebase-docker-image\node_modules\async\dist\async.js:3871:13
    at Request.request [as _callback] (C:\Users\astainba\AppData\Roaming\npm\node_modules\rebase-docker-image\index.js:395:7)
    at Request.self.callback (C:\Users\astainba\AppData\Roaming\npm\node_modules\rebase-docker-image\node_modules\request\request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (C:\Users\astainba\AppData\Roaming\npm\node_modules\rebase-docker-image\node_modules\request\request.js:1163:10)

**Comment by StefanScherer** [comment]
Oh dear. Well the error handling is still quite poor.
Can you share the complete command line that you used?
Do you want to rebase eg. a private image or other some special cases?

**Comment by AceHack** [comment]
@StefanScherer thanks for the quick response.  It's all against public images.  Let me give you a link to my repo.

This is the [docker file](https://github.com/AceHack/dotnet-docker-powershell/blob/master/dotnet/2.0/sdk-powershell/nanoserver-sac2016/amd64/Dockerfile) I was trying to rebase.

My [rebase command](https://github.com/AceHack/dotnet-docker-powershell/blob/master/deploy.ps1) is in this script but commented out for now.

I used to read

# push images
`docker push acehack/dotnet:2.0.5-sdk-powershell-2.1.4-nanoserver-sac2016`

# rebase for windows 1709
```
npm install -g rebase-docker-image
rebase-docker-image acehack/dotnet:2.0.5-sdk-powershell-2.1.4-nanoserver-sac2016 -t acehack/dotnet:2.0.5-sdk-powershell-2.1.4-nanoserver-1709 -b microsoft/dotnet:2.0.5-sdk-2.1.4-nanoserver-1709
```

I've created 'acehack/dotnet:2.0.5-sdk-powershell-2.1.4-nanoserver-1709' by other means now so if you are testing I'm guessing you would need to use another name since this one is already existing.

You can see my public images here
https://hub.docker.com/r/acehack/dotnet/tags/

Thanks so much for your help.

**Comment by StefanScherer** [comment]
@AceHack The command line should look like `-b microsoft/nanoserver:1709` - the option `-b` specifies the new base image which is one of the nanoserver images.

**Comment by AceHack** [comment]
Okay, I see thanks, I was hoping not to have to rebase .NET's image since they build differently for sac2016 and 1709.  I really wanted to rebase my stuff on top of the dotnet 1709 image not rebase my stuff and .NET on top of the nanoserver 1709 image.  Is there no way of doing this?

Thanks so much.

**Comment by StefanScherer** [comment]
Ah, I see. At the moment the tool only can replace the real base images

Well for a bigger base image maybe `-s` already works:

```powershell
rebase-docker-image `
  acehack/dotnet:2.0.5-sdk-powershell-2.1.4-nanoserver-sac2016 `
  -t acehack/dotnet:2.0.5-sdk-powershell-2.1.4-nanoserver-1709 `
  -s microsoft/dotnet:2.0.5-sdk-2.1.4-nanoserver-sac2016
  -b microsoft/dotnet:2.0.5-sdk-2.1.4-nanoserver-1709
```

I haven't fully tested, but this is how the command line should look like to specify the exact base image so that the tool can collect all of the source base image layers to replace with the new base image layers.

**Comment by AceHack** [comment]
@StefanScherer that appears to have worked great!! Thanks so much for your help.

**Comment by AceHack** [comment]
@StefanScherer I take that back, I'm getting the following error.

docker: Error response from daemon: container 87bbbcc6785f361a1a8583e0e3fe20f15a7b5de28889d8760abe96367ff3cd7b encountered an error during Start: failure in a Windows system call: The compute system exited unexpectedly. (0xc0370106).

**Comment by AceHack** [comment]
Command is

`docker run -it --rm acehack/dotnet:2.0.5-sdk-powershell-2.1.4-nanoserver3-1709 pwsh`

**Comment by StefanScherer** [comment]
Oh, well this method of rebasing is not guaranteed to work. Maybe the layers are incompatible.
My experience is that if the base image with its layers uses "RUN" instructions then this causes problems.
I only rebase images that just contain COPY layers and are based on the vanilla microsoft/nanoserver image.
