### ISSUE TITLE
Issue with 1809 image

### ISSUE THREAD

**Issue by deviantony** [StefanScherer/rebase-docker-image#5]
Hi @StefanScherer, hope you're doing well !

We're still using this tool to build our different Windows images for Portainer but it seems that we have an issue with the Windows 1809 image.

```
rebase-docker-image portainer/portainer:windows-amd64 -t portainer/portainer:windows1809-amd64 -b mcr.microsoft.com/windows/nanoserver:1809
Retrieving information about source image portainer/portainer:windows-amd64
Retrieving information about source base image mcr.microsoft.com/windows/nanoserver:10.0.14393.2551
/home/tony/.nvm/versions/node/v10.9.0/lib/node_modules/rebase-docker-image/index.js:405
      }/blobs/${manifestSourceBase.config.digest}`,
                                          ^

TypeError: Cannot read property 'digest' of undefined
    at getConfigOfSourceBaseImage (/home/tony/.nvm/versions/node/v10.9.0/lib/node_modules/rebase-docker-image/index.js:405:43)
    at /home/tony/.nvm/versions/node/v10.9.0/lib/node_modules/rebase-docker-image/node_modules/async/dist/async.js:3866:24
    at replenish (/home/tony/.nvm/versions/node/v10.9.0/lib/node_modules/rebase-docker-image/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/home/tony/.nvm/versions/node/v10.9.0/lib/node_modules/rebase-docker-image/node_modules/async/dist/async.js:983:17)
    at /home/tony/.nvm/versions/node/v10.9.0/lib/node_modules/rebase-docker-image/node_modules/async/dist/async.js:958:16
    at /home/tony/.nvm/versions/node/v10.9.0/lib/node_modules/rebase-docker-image/node_modules/async/dist/async.js:3871:13
    at Request.request [as _callback] (/home/tony/.nvm/versions/node/v10.9.0/lib/node_modules/rebase-docker-image/index.js:395:7)
    at Request.self.callback (/home/tony/.nvm/versions/node/v10.9.0/lib/node_modules/rebase-docker-image/node_modules/request/request.js:186:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/tony/.nvm/versions/node/v10.9.0/lib/node_modules/rebase-docker-image/node_modules/request/request.js:1163:10)
```

Based on the `mcr.microsoft.com/windows/nanoserver:1809` image. Do you have any recommendations for using this tool with the latest 1809 image?

Thanks again.

**Comment by StefanScherer** [comment]
Thanks @deviantony that's good to know that you're using this tool.
I'm using this tool with 1809 images with a little trick as I hadn't the time to dig deeper into the issue.
The MCR is more hidden what works and what does not, some API calls are disabled compared to Docker Hub. I don't know exactly if that is the problem here, but the following trick works for me.

Look at eg. https://github.com/StefanScherer/whoami/pull/10/files
I tag and push the mcr images to an own repository on Docker Hub and then use this tag for the rebase.
No Windows image is pushed to Docker Hub, only the metadata.
It was much easier to fix it this way.

**Comment by StefanScherer** [comment]
After each Patch Tuesday I have to push a new tag. I just did that for the latest like this:

```
docker pull mcr.microsoft.com/windows/nanoserver:1809
docker manifest inspect mcr.microsoft.com/windows/nanoserver:1809
docker tag mcr.microsoft.com/windows/nanoserver:1809 stefanscherer/nanoserver:10.0.17763.194
docker push stefanscherer/nanoserver:10.0.17763.194
```

**Comment by StefanScherer** [comment]
@deviantony with #5 merged and published it should work now.

I just tried this one:

```
rebase-docker-image portainer/portainer:windows-amd64 -t stefscherer/reb1:windows1809-amd64 -b mcr.microsoft.com/windows/nanoserver:1809 --verbose
```

**Comment by deviantony** [comment]
Great, thanks for the update.
