### ISSUE TITLE
Error: Error: MANIFEST_UNKNOWN

### ISSUE THREAD

**Issue by L3tum** [StefanScherer/rebase-docker-image#7]
This is probably my doing but in case it isn't I wanted to file an issue. Maybe you know what I'm doing wrong. 

I've set up a multiarch build on appveyor like you did with whoami, except it's an ASP.Net Core 2.1 base image. It's available for Windows 1703-1809, however because the build server is 1703 I have to rebase it for the other versions. 

Rebasing it to 1809 works fine, but neither 1709 nor 1803 work. They output the above error. 

Actually, I just checked again and apparently the tool tries to rebase the base Windows 1703 image and not the ASP.Net core image that was built on top, and probably fails at that because the base isn't published or something. Regardless it seems to work by specifying the -s sourcebase image as the asp.net core image. Thought I'd still open an issue as this is IMO useful information. 

Below is the relevant part of the log output. 

`Retrieving information about source base image registry-1.docker.io/microsoft/dotnet:10.0.14393.2551
Error: Error: MANIFEST_UNKNOWN
    at Request.request [as _callback] (C:\Users\appveyor\AppData\Roaming\npm\node_modules\rebase-docker-image\index.js:405:25)
    at Request.self.callback (C:\Users\appveyor\AppData\Roaming\npm\node_modules\rebase-docker-image\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\appveyor\AppData\Roaming\npm\node_modules\rebase-docker-image\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\appveyor\AppData\Roaming\npm\node_modules\rebase-docker-image\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)`

**Comment by StefanScherer** [comment]
Thanks for the report. Your assumption is correct, using `-s` helps the tool to find the exact source base image. Otherwise it just can use the `os.version` metadata from the source image and use that as a tag name. This works for `microsoft/nanoserver`, but not for other images.
